"""
Django settings for coreProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import mongoengine


## ----------------------------------------------------------------------------------------------------------------------- ##
## ------------------------------------------------ SECTION 0: ENV VARS -------------------------------------------------- ##

## ENV VARS 
# Choose environment: "dev" or "prod"
env = os.getenv("ENV", "dev")  # default to dev if ENV not set

# Load the corresponding .env file
load_dotenv(f".env.{env}")


## ----------------------------------------------------------------------------------------------------------------------- ##
## ----------------------------------------------------------------------------------------------------------------------- ##




## ----------------------------------------------------------------------------------------------------------------------- ##
## -------------------------------------------- SECTION 1: DJANGO'S SETTINGS --------------------------------------------- ##

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_URLCONF = 'coreProject.urls'


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1', 'yes']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

ALLOWED_HOSTS = [
    host.strip() 
    for host in os.getenv('ALLOWED_HOSTS', '').split(',') 
    if host.strip()
]


# Application definitions
THIRD_PARTY_APPS = [
    'ninja_extra',   
    'ninja_jwt',
]

INTERNAL_APPS = [
    'ms0_usersAndAuth',
]

# i can comment some of the defaul apps not needed here (such as the sessions app, since i use jwt). Note that these apps created tables in the default db when i first ran migrations
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + THIRD_PARTY_APPS + INTERNAL_APPS



## --------------- LOGGING ------------------

# -- creating a logs dir for each app
BASE_LOG_DIR = os.getenv("LOG_DIR", "/monitoring/log_files")
os.makedirs(BASE_LOG_DIR, exist_ok=True)

LOG_DIRS = {app: os.path.join(BASE_LOG_DIR, app) for app in INTERNAL_APPS}

# make sure the directories exist
for dir_path in LOG_DIRS.values():
    os.makedirs(dir_path, exist_ok=True)

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "json": {
#             "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
#             "fmt": "%(asctime)s %(levelname)s %(name)s %(message)s",
#         },
#     },
#     "handlers": {
#         app: {
#             "level": "INFO",
#             "class": "logging.RotatingFileHandler",
#             "filename": os.path.join(LOG_DIRS[app], f"{app}.log"),
#             "formatter": "json",
#             "maxBytes": 5 * 1024 * 1024,  # 5 MB
#             "backupCount": 3,             # keep last 3 log files
#         } for app in INTERNAL_APPS
#     },
#     "loggers": {
#         app: {
#             "handlers": [app],
#             "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
#             "propagate": False,
#         } for app in INTERNAL_APPS
#     },
# }
## ------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware", # CORS MIDDLEWARE. above common middleware (the one for all other requests. CORS must always be above common middleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ADDITION for CORS (where http request origins can come from)
if DEBUG:
    CORS_ALLOWED_ORIGINS = ["http://*", "https://*", "http://localhost:3000", "http://127.0.0.1:3000",]
    CSRF_TRUSTED_ORIGINS = ["http://*", "https://*", "http://localhost:3000", "http://127.0.0.1:3000",]
else:
    CORS_ALLOWED_ORIGINS = [
        origin.strip() 
        for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
        if origin.strip()
    ]
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() 
        for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
        if origin.strip()
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coreProject.wsgi.application'

# django ninja JWT settings
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # 'ROTATE_REFRESH_TOKENS': False,
    # 'BLACKLIST_AFTER_ROTATION': False,
    # 'UPDATE_LAST_LOGIN': False,

    # 'ALGORITHM': 'HS256',
    # 'SIGNING_KEY': SECRET_KEY,
    # 'VERIFYING_KEY': None,
    # 'AUDIENCE': None,
    # 'ISSUER': None,
    # 'JWK_URL': None,
    # 'LEEWAY': 0,

    # 'USER_ID_FIELD': 'id',
    # 'USER_ID_CLAIM': 'user_id',
    # 'USER_AUTHENTICATION_RULE': 'ninja_jwt.authentication.default_user_authentication_rule',

    # 'AUTH_TOKEN_CLASSES': ('ninja_jwt.tokens.AccessToken',),
    # 'TOKEN_TYPE_CLAIM': 'token_type',
    # 'TOKEN_USER_CLASS': 'ninja_jwt.models.TokenUser',

    # 'JTI_CLAIM': 'jti',

    # 'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    # 'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    # 'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

    # For Controller Schemas
    # # FOR OBTAIN PAIR
    # 'TOKEN_OBTAIN_PAIR_INPUT_SCHEMA': "ninja_jwt.schema.TokenObtainPairInputSchema",
    # 'TOKEN_OBTAIN_PAIR_REFRESH_INPUT_SCHEMA': "ninja_jwt.schema.TokenRefreshInputSchema",
    # # FOR SLIDING TOKEN
    # 'TOKEN_OBTAIN_SLIDING_INPUT_SCHEMA': "ninja_jwt.schema.TokenObtainSlidingInputSchema",
    # 'TOKEN_OBTAIN_SLIDING_REFRESH_INPUT_SCHEMA':"ninja_jwt.schema.TokenRefreshSlidingInputSchema",

    # 'TOKEN_BLACKLIST_INPUT_SCHEMA': "ninja_jwt.schema.TokenBlacklistInputSchema",
    # 'TOKEN_VERIFY_INPUT_SCHEMA': "ninja_jwt.schema.TokenVerifyInputSchema",
}


## ----------------------------------------------------------------------------------------------------------------------- ##
## ----------------------------------------------------------------------------------------------------------------------- ##


## ----------------------------------------------------------------------------------------------------------------------- ##
## ------------------------------------------------- SECTION 2: DATABASES ------------------------------------------------ ##

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {},
    'ms0_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('MS0_DB_NAME'),
        'USER': os.getenv('MS0_DB_USER'),
        'PASSWORD': os.getenv('MS0_DB_PASSWORD'),
        'HOST': os.getenv('MS0_DB_HOST'),
        'PORT': os.getenv('MS0_DB_PORT'),
    }
}

# Custom user model
AUTH_USER_MODEL = 'ms0_usersAndAuth.User'

# Database routing
DATABASE_ROUTERS = ['coreProject.db_router.AppDatabaseRouter']


## ----------------------------------------------------------------------------------------------------------------------- ##
## ------------------------------------------------ SECTION 2.1: MONGODB ------------------------------------------------- ##


# MongoDB Configuration
MONGODB_SETTINGS = {
    'db': os.getenv('MONGODB_DB'),
    'host': os.getenv('MONGODB_HOST'),
    'port': int(os.getenv('MONGODB_PORT', 27017)),
    # 'username': os.getenv('MONGODB_USERNAME'),
    # 'password': os.getenv('MONGODB_PASSWORD'),
    # 'authentication_source': os.getenv('MONGODB_AUTH_SOURCE'),
}

# Connect to MongoDB
try:
    mongoengine.connect(**MONGODB_SETTINGS)
    print("MongoDB connection established successfully!")
except Exception as e:
    if not DEBUG:
        raise ValueError(f"MongoDB connection failed in production: {str(e)}")
    else:
        print(f"MongoDB connection failed (development mode): {str(e)}")

## ----------------------------------------------------------------------------------------------------------------------- ##
## ----------------------------------------------------------------------------------------------------------------------- ##


## ----------------------------------------------------------------------------------------------------------------------- ##
## ----------------------------------------------------------------------------------------------------------------------- ##


## ----------------------------------------------------------------------------------------------------------------------- ##
## ------------------------------------------ SECTION 3: Password validation --------------------------------------------- ##

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

## ----------------------------------------------------------------------------------------------------------------------- ##
## ----------------------------------------------------------------------------------------------------------------------- ##




## ----------------------------------------------------------------------------------------------------------------------- ##
## ------------------------------------------ SECTION 4: Internationalization -------------------------------------------- ##

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


## ----------------------------------------------------------------------------------------------------------------------- ##
## -----------------------------------------------------------------------------------------------------------------------
